### ISSUE TITLE
Global or context Help Screen(s)

### ISSUE THREAD

**Issue by RoscoP** [Cretezy/lazyjj#13]
'h/?' brings up a help screen that talks about context help, or maybe a global level help screen like 'less' (to start out with).

**Comment by Cretezy** [comment]
I've implemented a help menu in https://github.com/Cretezy/lazyjj/pull/37\

![image](https://github.com/Cretezy/lazyjj/assets/2672503/3ce04eb4-4799-429c-b403-fc79efc6488d)

Should be merged shortly, for the v0.2 release
