### ISSUE TITLE
Branches tab

### ISSUE THREAD

**Issue by Cretezy** [Cretezy/lazyjj#3]
It would be great if lazyjj had a "Branches" tab which listed branches and the current commit they are pointed at.

Potential actions:
- Create branch
- Delete/forget branch
- Rename branch
- Track/untrack branch?

Additionally, when on the "Log" tab, an action to set a change to a branch could be added. Once the action triggered, a menu to select (or create) a branch would be shown.

**Comment by maralorn** [comment]
I notice that in practice setting a branch (and then immediately pushing it) is something I need very often.

**Comment by Cretezy** [comment]
@maralorn I agree, an option to push after setting sounds like a great idea.

**Comment by Cretezy** [comment]
Since [templating for branches](https://github.com/martinvonz/jj/commit/12b873e1eff64ed3bca9bf4d1a7547c7c0c98bfd) is coming soon, this feature will require 0.18 (schedule for release in ~1 week). 

I have a WIP implementation: https://github.com/Cretezy/lazyjj/pull/18
