### ISSUE TITLE
Problems on Windows

### ISSUE THREAD

**Issue by fleimgruber** [Cretezy/lazyjj#39]
lazyjj 0.2.0 via `cargo +nightly install --git https://github.com/Cretezy/lazyjj.git --locked`.

- Navigation with `j/k` executes twice, so can only navigate two rows at a time.
- Probably related to that (due to "passing over" the line in between?) the "Diff" pane looks garbled (i.e. a partial mix of different commits overlaid) after navigation.

I tested with Windows Terminal and Contour, same behaviour so I suspect some Windows specific issue.

Happy to help debugging.

**Comment by Cretezy** [comment]
I think this is due to the removal of the check if a key is being pressed down (as opposed to being raised).

I will release a v0.2.1 with a fix for this today.

**Comment by Cretezy** [comment]
v0.2.1 is out with a bug fix for this issue. Please let me know if this is happening in any other places.

Thanks for the report!

**Comment by fleimgruber** [comment]
@Cretezy I just used lazyjj again at v0.4.2 and still see the problem from second bulletpoint of OP.
