### ISSUE TITLE
Push selected commit

### ISSUE THREAD

**Issue by maralorn** [Cretezy/lazyjj#47]
I found it a bit unintutive that `p` seems to always push `@` instead of the change selected in the log.

**Comment by Cretezy** [comment]
`p` does `jj git push`, which does: "By default, pushes any branches pointing to `remote_branches(remote=<remote>)..@`".

I believe we should probably do `remote_branches(remote=<remote>)..$CURRENT_CHANGE_ID`, which would match the behavior you are expecting.

**Comment by Cretezy** [comment]
Fixed in https://github.com/Cretezy/lazyjj/pull/48
