### ISSUE TITLE
Diff is not completely redrawn

### ISSUE THREAD

**Issue by istudyatuni** [Cretezy/lazyjj#49]
<details><summary>Screenshots</summary>
<p>

Root commit:
![image](https://github.com/Cretezy/lazyjj/assets/43654815/5f497c2b-6e1a-4ed9-a16f-288675bf276b)

Commit after root:
![image](https://github.com/Cretezy/lazyjj/assets/43654815/094fc748-ed79-446e-8942-3b399f49a851)

</p>
</details>

**Comment by Cretezy** [comment]
That is strange, I have not seen this yet. Could you give me a bit more information on how to reproduce this issue?

- OS
- Terminal
- Shell
- Repo
- Steps to trigger

**Comment by istudyatuni** [comment]
- Os: NixOS
- Terminal: Alacritty
- Shell: Zsh + Oh-my-zsh (it seems that this is doesn't affect rendering)
- Repo: https://github.com/istudyatuni/snaks
- Steps to reproduce

```sh
cd /tmp && mkdir test && cd test
# copy https://github.com/istudyatuni/snaks/blob/master/.justfile to a.txt
jj git init
jj new
lazyjj
```

**Comment by istudyatuni** [comment]
More rendering issues:
```just
test:
	nix-shell --pure \
		-p inotify-tools just \
		--run 'inotifywait -q -m -r -e modify /tmp/asdfa | while read; do echo test; done'
```
<details><summary>Screenshot</summary>
<p>

![image](https://github.com/Cretezy/lazyjj/assets/43654815/531b9162-952b-4ee2-aea5-a2f9f91a907a)

</p>
</details>

**Comment by istudyatuni** [comment]
Similar issue: https://github.com/martinvonz/jj/issues/4001
